agents:
  queue: raftz-linux-amd64

cache:
  paths:
    - ".zig-cache"
    - "/tmp/raftz-ci-cache"
  name: "raftz-${BUILDKITE_COMMIT}-nightly-cache"

steps:
  - label: "Nightly fuzz ({{matrix}})"
    key: fuzz
    command: bash .buildkite/scripts/run.sh x86_64 bash .buildkite/scripts/with-fuzz-artifacts.sh scripts/run-fuzz.sh fuzz-{{matrix}} 1M
    matrix: [codec, wal, confchange]
    timeout_in_minutes: 60

  - label: "Nightly fuzz (sim)"
    key: fuzz-sim
    command: bash .buildkite/scripts/run.sh x86_64 bash .buildkite/scripts/with-fuzz-artifacts.sh scripts/run-fuzz.sh fuzz-sim 100K
    timeout_in_minutes: 60

  - label: "Nightly fuzz (wal-crash)"
    key: fuzz-wal-crash
    command: bash .buildkite/scripts/run.sh x86_64 bash .buildkite/scripts/with-fuzz-artifacts.sh scripts/run-fuzz.sh fuzz-wal-crash 10K
    timeout_in_minutes: 60
